###################################################
#                                                 #
# Home Assistant Main Configuration File          #
#                                                 #
###################################################

homeassistant:
  auth_providers: 
   - type: homeassistant
   - type: legacy_api_password
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 47
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

####################################################
#                                                  #
#               Frontend/Themes                    #
#                                                  #
####################################################
frontend:
  themes: !include_dir_merge_named themes

####################################################
#                                                  #
#             Lovelace/CustomUpdater               #
#                                                  #
####################################################
lovelace:
  mode: yaml

wake_on_lan:

google:
  client_id: !secret google_clientid
  client_secret: !secret google_secret
# Enables configuration UI
config:

http:
  api_password: !secret http_password
  cors_allowed_origins:
    - http://10.10.20.216:7080
    - https://reformedreality.com
    - http://reformedreality.com
    - https://google.com
    - https://home-assistant.io
    - https://api.ai
  ip_ban_enabled: True
  login_attempts_threshold: 5
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url:
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
websocket_api:

system_health:

owntracks:
  max_gps_accuracy: 200
  #mqtt_topic: "owntracks/#"

shopping_list:

stream:
ffmpeg:

####################################################
#                                                  #
#                     Alarm                        #
#                                                  #
####################################################

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: 1234567890
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
####################################################
#                                                  #
#                 Geolocation                      #
#                                                  #
####################################################
zone: !include zones.yaml
mqtt: !include mqtt.yaml

###############  Earth Quake  ######################
geo_location:
  - platform: usgs_earthquakes_feed
    #feed_type: 'past_day_all_earthquakes'
    feed_type: 'past_hour_significant_earthquakes'
    radius: 100
    minimum_magnitude: 0.0
    latitude: !secret latitude2
    longitude: !secret longitude2

####################################################
#                    Alexa                         #
#               Smart Home Speakers                #
#             Powered by Haaska Skill              #
####################################################
### URL https://github.com/mike-grant/haaska/wiki
alexa:
  smart_home:
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    filter:
      include_entities:
        - switch.air
        - switch.air2
        - switch.air3
        - switch.dsm01
        - switch.fritz_dect_200_1
        - switch.fritz_dect_200_2
        - switch.nico_computer
        - sensor.miflora_1_temperature
        - media_player.sony_bravia_tv
        - sensor.bathroom_temperature
        - sensor.bedroom_temperature
        - sensor.living_room_temperature
      include_domains:
        #- switch
        #- light
        #- script
        #- alarm_control_panel
        #- climate
        - media_player
      exclude_entities:
        #- switch.foscam_state
        #- switch.foscam_motion
        - media_player.nicolo_s_alexa_apps
        - media_player.nicolo_s_bose_home_speaker_500
        - media_player.this_device
        - media_player.echo_dot_di_nicolo
        - media_player.this_device_2
        - media_player.salotto
        - media_player.kd_55xf9005
        - switch.fluxer
        - climate.living_room
        - climate.bathroom
        - climate.living_room
        - sensor.bathroom_temperature
        - sensor.bedroom_temperature
        - sensor.living_room_temperature
      exclude_domains:
        - automation
        - automation
        - group
        - lock
        - cover
        - alert
        - switch
        - script
        - light
        - climate
        #- media_player

        
    entity_config:
      switch.nico_computer:
        name: il PC
        description: Computer
        display_categories: SWITCH
      switch.dsm01:
        name: Synology
        description: Il Nas
        display_categories: SWITCH
      group.all_lights:
        name: Tutte le luci
        description: Tutte le luci
      media_player.sony_bravia_tv:
        name: TV Mamma
        description: La televisione di Mamma
        display_categories: SWITCH
      switch.air:
        name: Aria Calda
        description: l'aria calda
        display_categories: SWITCH
      switch.air2:
        name: Aria Fredda
        description: l'aria fredda
        display_categories: SWITCH
      switch.air3:
        name: Deumidificatore
        description: il deumidificatore
        display_categories: SWITCH


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
hassio:
shelly:
  discovery: true  #add all devices (default)
  username: !secret shellyuser
  password: !secret shellypwd
  additional_information: true
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'it'
    base_url: https://yourdynamicdns:8123


speedtestdotnet:
  server_id: 123
  scan_interval:
    hours: 4
  monitored_conditions:
    - ping
    - download
    - upload

# Cloud
cloud:
light: !include light.yaml
camera: !include camera.yaml
weblink: !include weblink.yaml
group: !include groups.yaml
automation: !include automations.yaml
#automation old: !include_dir_merge_list automation

script: !include scripts.yaml
shell_command: !include shell_commands.yaml
device_tracker: !include device_tracker.yaml
sensor: !include sensor.yaml
cover: !include cover.yaml
media_player: !include media_player.yaml
switch: !include switch.yaml
notify: !include notify.yaml
binary_sensor: !include binary_sensors.yaml

alexa_media:
  accounts:
    - email: !secret amazonemail
      password: !secret amazonpwd
      #url: !secret amazonurl
      url: !secret amazonurl_it
      scan_interval: 30
telegram_bot:
  platform: polling
  api_key: !secret telegram_apikey
  allowed_chat_ids:
    - !secret telegram_clientid
    - !secret telegram_clientid2

####################################################
#                                                  #
#                   Recorder                       #
#                                                  #
####################################################

recorder:
   db_url: !secret dburl
   purge_keep_days: 7
   purge_interval: 1
   exclude:
    domains:
      - automation
      - weblink
      - updater
      - sensor
      - switch
      - mqtt
    entities:
      - sensor.date
      - sun.sun
   include:
    entities:
      - cover.shelly_shsw_25_e6704f
      - switch.shelly_shsw_25_68796e_1
      - switch.shelly_shsw_25_68796e_2
      - switch.shelly_shsw_25_686d62_1
      - switch.shelly_shsw_25_686d62_2
      - switch.shelly_shsw_25_687269_1
      - switch.shelly_shsw_25_687269_2
      - switch.shelly_shsw_25_e5e601_1
      - switch.shelly_shsw_25_e5e601_2
      - switch.shelly_shplg_s_041a07
      - switch.shelly_shplg_s_0409b4
      - switch.air
      - switch.air2
      - switch.air3
      - switch.nico_computer
      - switch.shelly_shplg_s_7a33ff
      - switch.fritz_box_guest_wifi
      - switch.shelly_shplg_s_041a76
      - switch.ciabatta_rack_fritz_dect_200_1
      - switch.presa_rasp_pi3_fritz_dect_200_2       
      - switch.shelly_shplg_s_04169c
      - switch.shelly_shplg_s_5b2502
      - sensor.shelly_shwt_1_694834_flood
      - sensor.shelly_shwt_1_694834_temperature
      - sensor.potenza_istantanea
      - sensor.living_room_heating
      - sensor.living_room_humidity
      - sensor.living_room_power
      - sensor.living_room_temperature
      - sensor.mamma_battery
      - sensor.nico_battery
      - sensor.processor_use
      - sensor.shelly_flood_battery

####################################################
#                                                  #
#                   History                        #
#                                                  #
####################################################
# Enables support for tracking state changes over time
history:
  #exclude:
    #domains:
      #- automation
      #- weblink
      #- updater
    #entities:
      #- sensor.date
  #include:
    #domains:
      #- sensor
      #- switch
      #- media_player
      #- light

####################################################
#                                                  #
#                   LogBook                        #
#                                                  #
####################################################

# View all events in a logbook
logbook:
logger:
  default: warn
####################################################
#                                                  #
#                   Database                       #
#                                                  #
####################################################

influxdb:
  host: 1.1.1.1
  port: 8086
  database: home_assistant   
  username: !secret influxdb_user
  password: !secret influxdb_pwd
  #max_retries: 3
  #default_measurement: state


###################################################
#                                                 #
#                   IFTTT                         #
#                                                 #
###################################################

ifttt:
  key: !secret ifttt_key


###################################################
#                                                 #
#                 Smart Home                      #
#                                                 #
###################################################

tado:
  username: !secret tado_user
  password: !secret tado_pwd

fritzbox:
  devices:
    - host: fritz.box
      username: !secret fritz_user
      password: !secret fritz_pwd 

fritzbox_tools:
  host: 1.1.1.1
  username: !secret fritz_user
  password: !secret fritz_pwd

####################################################
#                                                  #
#              Input Slider and Boolean            #
#                                                  #
####################################################

#input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number

####################################################
#                                                  #
#               Panel Iframe                       #
#                                                  #
####################################################


####################################################
#                                                  #
#               Panel Custom                       #
#                                                  #
####################################################


####################################################
#                                                  #
#             Restfull commands                    #
#                                                  #
####################################################

rest_command:
  google_backup:
    url: 'http://x.x.x.x:8055/gb/doBackup'
    timeout: '300'
  ss_cookie:
    url: !secret ss_cookie
    method: get
    verify_ssl: false
  ss_preset_home:
    url: !secret ss_preset_home
    method: get
    verify_ssl: false
  ss_preset_living:
    url: !secret ss_preset_living
    method: get
    verify_ssl: false
  ss_preset_bedroom:
    url: !secret ss_preset_bedroom
    method: get
    verify_ssl: false
  ss_preset_rack:
    url: !secret ss_preset_rack
    method: get
    verify_ssl: false
  ss_home_on:
    url: !secret ss_home_on
    method: get
    verify_ssl: false
  ss_home_off:
    url: !secret ss_home_off
    method: get
    verify_ssl: false


####################################################
#                                                  #
#                    Weather                       #
#                                                  #
####################################################

weather:
  # - platform: openweathermap
  #   api_key: !secret openweathermap
  - platform: darksky
    api_key: !secret darksky
    mode: daily
